added more automation for data creation
joshcwinton/SHRDLUOnline pull request #54
Opened 2021-03-23 18:47 UTC by donaldchen34

Description of PR here...
-Added synonym checks for the nouns too
-The file now reads the sentences_to_train_on.txt to see what sentences to create training data on
-The file saves all unique sentences in unique_sentences.txt now
Issue: Closes #

## Changes
### Frontend:
- 
### Backend:
- Updated data_creation.py

2021-03-24 01:17 UTC, JasperCheung commented on backend/machine learning/data_creation.py
> +with open(TRAINING_SENTENCES_FILE,'r') as csv_file:
can you write a main function and put this in it? `if __name__ == '__main__'`

2021-03-24 01:18 UTC, JasperCheung commented on backend/machine learning/data_creation.py
>  data = [] #create_Data stores everything in data
move this down into the main function.

2021-03-24 01:20 UTC, JasperCheung requested changes
- Could you rename the `machine learning` dir to `machine_learning`?
- ~~running this doesn't do anything for me.~~
- It might make sense to .gitignore the `/data` folder. I don't think we wanna push a ton of sentences to the repo.
- add some comments homie
- add a readme

2021-03-25 18:53 UTC, donaldchen34 commented on backend/machine_learning/data_creation.py
> +def save_Sentence_Structure(action,noun,color,sentence,relative_action=None,
This is the new method of adding sentences:
Sentences will be added based on sentence structures so 
"Add the red cube near the green sphere" = "Add the green pyramid above the blue cube"
Both sentence structures are seen <Target_action> the <color> <noun> <rel_action> the <rel_obj_color> <rel_obj>
All unique combinations will be created based on the sentence structure

2021-03-26 18:16 UTC, donaldchen34 commented on backend/machine_learning/data_creation.py
> +                        data.append([new_sentence2,action,noun,color,relative_action,
Data was using noun_synoynm as target. It should be noun

2021-04-09 18:52 UTC, closed without merging