Relative Actions
joshcwinton/SHRDLUOnline pull request #77
Opened 2021-04-17 15:38 UTC by donaldchen34

Added undo function and routes for undo and clear

Issue: Closes #

## Changes
### Frontend:
- 
### Backend:
-

2021-04-17 16:14 UTC, joshcwinton approved these changes
Looks good 👍 

I think the ML stuff got pulled in here because the branch isn't based on main but nbd

LGTM 💰

2021-04-17 19:39 UTC, JasperCheung requested changes

2021-04-17 19:39 UTC, JasperCheung commented on backend/app.py
> +@app.route('/clear', methods=['GET'])
should return a message like "Undo Action!"
 ```def chatbot_route():
    if request.method == 'POST':
        post_data = request.get_json()
        user_res = post_data["user"]
        bot_res = chatbot(user_res)
        return jsonify({"SHRDLU": bot_res})
    return jsonify({"get": "requested"})
```

2021-04-17 19:39 UTC, JasperCheung commented on backend/app.py
> +def clear_route():
same thing as above

2021-04-18 14:32 UTC, svhnstorage approved these changes

2021-04-22 17:22 UTC, joshcwinton requested changes

2021-04-22 17:22 UTC, joshcwinton commented on backend/environment.py
> +    MESSAGES.append({"name": "Me", "Clear board": inputMessage})
the message part of these should have the key `text` and value the actual message

i.e. `{"name": "Me", "text": inputMessage}`

see `updateHistory()`

2021-04-26 14:06 UTC, JasperCheung commented
Refer to newer pr

2021-04-26 14:06 UTC, closed without merging